### ISSUE TITLE
unable to create complex scenario given-when-then-when-then

### ISSUE THREAD

**Issue by mruanova** [thomhurst/BDTest#24]
[Test]
        [ScenarioText("end to end testing scenario create and find")]
        public async Task FindNonExistingAccountReturnsNotFound()
        {
            await When(() => AccountSteps.CreateAnAccount())
                .Then(() => HttpAssertions.TheHttpStatusCodeIs(HttpStatusCode.OK))
                .When(() => AccountSteps.FindAccount(12345)) // <- CANNOT RESOLVE SYMBOL WHEN
                .Then(() => HttpAssertions.TheHttpStatusCodeIs(HttpStatusCode.NotFound))
                .BDTestAsync();
        }

**Comment by thomhurst** [comment]
@mruanova This is by design. For clarity, I'd have that as two different test cases:

```csharp
[Test]
[ScenarioText("Create Account Returns OK")]
public async Task CreateAccountReturnsOK()
{
  await When(() => AccountSteps.CreateAnAccount())
  .Then(() => HttpAssertions.TheHttpStatusCodeIs(HttpStatusCode.OK))
  .BDTestAsync();
}

[Test]
[ScenarioText("Find Non-Existing Account Returns Not Found")]
public async Task FindNonExistingAccountReturnsNotFound()
{
  await Given(() => AccountSteps.CreateAnAccount())
  .When(() => AccountSteps.FindAccount(12345)) // <- CANNOT RESOLVE SYMBOL WHEN
  .Then(() => HttpAssertions.TheHttpStatusCodeIs(HttpStatusCode.NotFound))
  .BDTestAsync();
}
```
